pipeline {

    agent any

    environment {
        POM = readMavenPom()
    }

    stages {
        stage("Compilation") {
            steps {
                dir('spring-jenkins-pipeline') {
                    echo "version = ${POM}"

                    script {
                        if (isUnix()) {
                            sh "./mvnw clean install -DskipTests"
                        } else {
                            bat "./mvnw.cmd clean install -DskipTests"
                        }
                    }
                }
            }
        }

        stage("Running unit tests") {
            steps {
                dir('spring-jenkins-pipeline') {
                    script {
                        try {
                            if (isUnix()) {
                                sh "./mvnw test -Punit"
                            } else {
                                bat "./mvnw.cmd test -Punit"
                            }
                        } catch (err) {
                            step([$class: 'JUnitResultArchiver', testResults: '**/target/surefire-reports/TEST-*UnitTest.xml'])
                            throw err
                        }
                        junit '**/target/surefire-reports/TEST-*UnitTest.xml'
                    }
                }
            }
        }

        stage("Code analysis - Sonar") {
            steps {
                dir('spring-jenkins-pipeline') {
                    withSonarQubeEnv('Local SonarQube') {
                        sh "./mvnw sonar:sonar"
                    }
                }
            }
        }

        stage("Quality Gate") {
            steps {
//                timeout(time: 1, unit: 'MINUTES') {
//                    waitForQualityGate abortPipeline: true
//                }
                script {
                    timeout(time: 1, unit: 'MINUTES') {
                        def qg = waitForQualityGate()
                        if (qg.status != 'OK') {
                            error "Pipeline aborted due to quality gate failure: ${qg.status}"
                        }
                    }
                }
            }
        }
    }
}